name: Fetch latest movies (every 6h)

on:
  schedule:
    - cron: "0 */6 * * *"  
  workflow_dispatch:
  push:
    paths:
      - "scripts/**"
      - ".github/workflows/fetch.yml"
      - "requirements.txt"

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch TMDB movies (max 10)
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
          TMDB_REGION: ${{ secrets.TMDB_REGION }}
          DAYS_BACK: "30"
        run: |
          python scripts/fetch_tmdb.py

      - name: Commit & push if changed
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add docs/data/movies.json docs/data/movie/*.json
            git commit -m "chore: refresh movies data [skip ci]"
            git push
          else
            echo "No changes."
          fi
